on:
  workflow_dispatch
  

jobs:
  convert_docs:
    runs-on: ubuntu-latest
    name: Convert documentation
    steps:
    - name: Hello world action step
      id: hello
      uses: shaydewael/docs-conversion@v0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        schema: 'jekyll-template.yml'
        input: 'docs/_basic'
        output: 'compiled'
