on:
  push:
    branches: [ 'main' ]

jobs:
  convert_docs:
    runs-on: ubuntu-latest
    name: Convert documentation
    steps:
    - name: Hello world action step
      id: hello
      uses: shaydewael/template-conversion
      with:
        template: 'jekyll-template.yml' # fake for now
        source: '/docs/_basic'
        output: '/docs/_basic_revised'
