on:
  workflow_dispatch
  

jobs:
  convert_docs:
    runs-on: ubuntu-latest
    name: Convert documentation
    steps:
    - name: Hello world action step
      id: hello
      uses: shaydewael/docs-conversion@v0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schema: 'test'
        input: 'docs'
        output: 'compiled'
